### ISSUE TITLE
Crashing at appstart

### ISSUE THREAD

**Issue by jesusspr** [hsangtini/flutter_admob_app_open#10]
![Screenshot 2021-04-19 at 10 51 10](https://user-images.githubusercontent.com/74351426/115208712-2867e680-a0fd-11eb-9c09-158cce909f9a.png)

  WidgetsFlutterBinding.ensureInitialized();
final admobAppId = "I hide my id"; 
  final appAppOpenAdUnitId = "I hide my id";
  AdRequestAppOpen targetingInfo = AdRequestAppOpen(
    keywords: <String>['flutterio', 'beautiful apps'],
    contentUrl: 'https://flutter.io',
    testDevices: <String>[], // Android emulators are considered test devices
    nonPersonalizedAds: true,
  );
  await FlutterAdmobAppOpen.instance.initialize(
    appId: admobAppId,
    appAppOpenAdUnitId: appAppOpenAdUnitId,
    targetingInfo: targetingInfo,
  );

AndroidManifest

![Screenshot 2021-04-19 at 10 54 23](https://user-images.githubusercontent.com/74351426/115209142-9c09f380-a0fd-11eb-8fd1-10c6dacfa720.png)

flutter doctor -v

[✓] Flutter (Channel master, 2.2.0-11.0.pre.127, on macOS 11.2.1 20D74 darwin-x64, locale en-ES)
    • Flutter version 2.2.0-11.0.pre.127 at /Users/jesus/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb73516739 (4 days ago), 2021-04-15 01:42:49 -0700
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jesus/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • SM G973F (mobile) • R58N53BE4HW • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.128

**Comment by phanvanluan94** [comment]
The same issue, that seems this plugin got affected by new version of **google_mobile_ads** plugin recently.
<img width="1227" alt="Screen Shot 2021-05-19 at 13 06 22" src="https://user-images.githubusercontent.com/22259333/118764110-2a12fe80-b8a3-11eb-90a1-e1b305e84c33.png">

**Comment by KaelTeck** [comment]
The same issue here. The app is crashing on start after adding the new google ads package. Please help.
