### ISSUE TITLE
Do not work on IOS 14.2 and android

### ISSUE THREAD

**Issue by antonmolchan** [hsangtini/flutter_admob_app_open#2]
Hi, i am try to use your library and have some exceptions, maybe you know how to fix it.
Ios log
`Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"20","method":"getObject","params":{"isolateId":"isolates/3678897934303463","objectId":"libraries/@1041171358"}}`
Android app opens ok, but on splash screen ad do not displayed

**Comment by hsangtini** [comment]
For some reasons you should check back:
- Your internet network
- The ads may not be downloaded at the first time yet from admob
- Try pause and resume the app a couple of times.
