### ISSUE TITLE
Error: Can not show ad on Android

### ISSUE THREAD

**Issue by d-apps** [hsangtini/flutter_admob_app_open#3]
When I try to use your package I get this error and the ad doesn't show:

```
D/AppOpenManager(16059): Can not show ad.
D/AppOpenManager(): onStart.
```

targetSDK: 29
minSDK: 21
Tested: Android 5.0

I only tested with Test App ID and and Test App Open Ad Unit.

**Comment by Namdh1212** [comment]
metoo

**Comment by devuserPP** [comment]
same for me. I opened your [example](https://github.com/hsangtini/flutter_admob_app_open/tree/master/example) , I tested with App open Ad unit "ca-app-pub-3940256099942544/3419835294" and  Test App ID "ca-app-pub-3940256099942544~3347511713" according [this](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml) and same error "Can not show ad", I can share whole log, if necessary

**Comment by phurblood** [comment]
Still no answer?

**Comment by hsangtini** [comment]
For some reasons you should check back:
- Your internet network
- The ads may not be downloaded at the first time yet from admob
- Try pause and resume the app a couple of times.

**Comment by SidneyCampos** [comment]
Same problem here
