### ISSUE TITLE
Unable to run on debug mode

### ISSUE THREAD

**Issue by phanvanluan94** [hsangtini/flutter_admob_app_open#7]
I got this issue as screenshot when trying to run application up.
<img width="568" alt="Screen Shot 2021-03-15 at 12 04 15" src="https://user-images.githubusercontent.com/22259333/111105988-c6104900-8586-11eb-9150-12c46312c887.png">
google_mobile_ads: ^0.11.0+3
flutter_admob_app_open: ^1.0.0

**Comment by hsangtini** [comment]
Please update version 1.0.1.

**Comment by phanvanluan94** [comment]
It's fixed. 
Thank you.
